-- =====================================================================
-- Development seed: a shared activity library to build and test the screens with.
--
-- `supabase db reset` runs this after the migrations. It is sample content, not the
-- production library, which is loaded by Cognicopia through the service role. It holds no
-- people and no resident data.
--
-- What is in it (104 items):
--   activities     movement, music, games, printable sheets, sensory activities and coloring
--                  pages, for every stage, with the themes each fits;
--   trivia         short sets of familiar sayings, songs and everyday facts, with answers;
--   reminiscence   40 conversation starters, ten for each decade from the 1940s to the 1970s,
--                  each with the senses it draws on and what to say next.
--
-- The payloads follow lib/domain/content.ts (schema_version 1). A test
-- (tests/db/seed.test.ts) checks every one of them against that schema, and another checks
-- the wording of the prompts. The `generator` names are the activity ids the facility
-- planner already uses (src/services/facilityPlanner.ts).
--
-- This file is written by a script from a table of items: edit supabase/seed-source/items.mjs and
-- run `npm run seed:build` (in platform/) rather than editing the SQL by hand. A test fails if the two
-- are out of step.
-- =====================================================================

insert into public.content_items (id, title, category, dementia_stage, content_payload) values
  ('5eed0000-0000-4000-8000-000000000001', 'Sing-along classics', 'music', 'universal',
   '{"schema_version":1,"summary":"Public-domain classics in very large type to sing together.","minutes":20,"group_friendly":true,"sensory":true,"formats":["active","printable"],"themes":["music"],"template":{"generator":"lyric-sheet","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000002', 'Chair yoga', 'movement', 'universal',
   '{"schema_version":1,"summary":"Gentle seated stretches, led from the front of the room.","minutes":20,"group_friendly":true,"sensory":true,"formats":["active"],"template":{"generator":"chair-yoga","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000003', 'Large-print word search', 'word', 'early',
   '{"schema_version":1,"summary":"A 12 or 15 square word search with the words listed beneath it.","minutes":20,"group_friendly":false,"sensory":false,"formats":["games","printable"],"template":{"generator":"search-large","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000004', 'Guided word search', 'word', 'middle',
   '{"schema_version":1,"summary":"A small 8 square word search; the first letter of each word is boxed.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"],"template":{"generator":"search-guided","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000005', 'Line tracing', 'movement', 'late',
   '{"schema_version":1,"summary":"Thick paths to trace with a finger or a marker: fine motor, one at a time.","minutes":15,"group_friendly":false,"sensory":true,"formats":["printable"],"template":{"generator":"line-tracing","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000006', 'Coloring page', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold adult line art; the detail of the picture follows the stage.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"template":{"generator":"cognicopia-coloring","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000007', 'Number ladders', 'numbers', 'early',
   '{"schema_version":1,"summary":"Counting on by 1s, 2s, 5s and 10s.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"],"template":{"generator":"number-ladder","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000008', 'Letter tracing', 'letters', 'late',
   '{"schema_version":1,"summary":"Very large letters to trace: tactile and calm.","minutes":15,"group_friendly":false,"sensory":true,"formats":["printable"],"template":{"generator":"letter-tracing","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000009', 'Orientation board', 'multisensory', 'universal',
   '{"schema_version":1,"summary":"A giant-type board for the day, the date and the weather.","minutes":10,"group_friendly":true,"sensory":true,"formats":["printable"],"template":{"generator":"orientation-board","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000010', 'Memory lane', 'word', 'universal',
   '{"schema_version":1,"summary":"Reminiscence prompts with no right or wrong answers.","minutes":30,"group_friendly":true,"sensory":false,"formats":["reminiscence"],"template":{"generator":"memory-lane","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000011', 'Walking club', 'movement', 'early',
   '{"schema_version":1,"summary":"A slow stroll, indoors or out, with a stop to notice something along the way.","minutes":25,"group_friendly":true,"sensory":true,"formats":["active"],"themes":["spring","summer","autumn","garden"],"steps":["Choose a flat, well-lit route and a point to stop.","Bring water and a chair for anyone who wants to rest.","Name one thing to look for before you set off."]}'),
  ('5eed0000-0000-4000-8000-000000000012', 'Stretch and sway to the big bands', 'movement', 'early',
   '{"schema_version":1,"summary":"Seated stretches and slow swaying to big band recordings.","minutes":20,"group_friendly":true,"sensory":true,"formats":["active"],"themes":["nostalgia-1940s","music"]}'),
  ('5eed0000-0000-4000-8000-000000000013', 'Seated twist to the sixties', 'movement', 'middle',
   '{"schema_version":1,"summary":"A gentle seated twist to 1960s dance songs; arms only for anyone who prefers.","minutes":15,"group_friendly":true,"sensory":true,"formats":["active"],"themes":["nostalgia-1960s","music"]}'),
  ('5eed0000-0000-4000-8000-000000000014', 'Scarf dancing', 'movement', 'middle',
   '{"schema_version":1,"summary":"Light scarves waved slowly to familiar music, seated or standing with support.","minutes":20,"group_friendly":true,"sensory":true,"formats":["active"],"themes":["music"],"materials":["Light chiffon scarves","Familiar music"]}'),
  ('5eed0000-0000-4000-8000-000000000015', 'Balloon volley', 'movement', 'universal',
   '{"schema_version":1,"summary":"Keep a balloon in the air together, seated, at a gentle pace.","minutes":15,"group_friendly":true,"sensory":true,"formats":["active","games"],"themes":["summer"]}'),
  ('5eed0000-0000-4000-8000-000000000016', 'Beanbag targets', 'movement', 'universal',
   '{"schema_version":1,"summary":"Seated tosses at a tabletop target, with scores to add.","minutes":20,"group_friendly":true,"sensory":true,"formats":["active","games"],"template":{"generator":"beanbag-target","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000017', 'Seated rhythm', 'movement', 'universal',
   '{"schema_version":1,"summary":"Clap and tap patterns everyone follows in time.","minutes":15,"group_friendly":true,"sensory":true,"formats":["active"],"themes":["music"],"template":{"generator":"seated-rhythm","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000018', 'Paper airplanes', 'movement', 'early',
   '{"schema_version":1,"summary":"Fold paper airplanes and fly them down a taped runway.","minutes":25,"group_friendly":true,"sensory":false,"formats":["active","games"],"themes":["aviation"],"materials":["Plain paper","Masking tape for the runway"],"steps":["Fold one airplane together first, a step at a time.","Mark the runway and take turns to fly.","Measure and cheer the longest glide."]}'),
  ('5eed0000-0000-4000-8000-000000000019', 'Planting herbs', 'multisensory', 'middle',
   '{"schema_version":1,"summary":"Pot basil, mint or parsley and rub a leaf to smell it.","minutes":30,"group_friendly":true,"sensory":true,"formats":["active","sensory"],"themes":["spring","garden","home-kitchen"],"materials":["Small pots","Potting soil","Herb seedlings that are safe if touched or tasted"],"steps":["Check for plant or soil allergies first.","Hand over one pot and one seedling at a time."]}'),
  ('5eed0000-0000-4000-8000-000000000020', 'Flower arranging', 'multisensory', 'early',
   '{"schema_version":1,"summary":"Cut and arrange fresh flowers for the dining room.","minutes":30,"group_friendly":true,"sensory":true,"formats":["active","sensory"],"themes":["spring","garden"],"materials":["Fresh flowers","Blunt scissors","Small vases"]}'),
  ('5eed0000-0000-4000-8000-000000000021', 'Music and humming circle', 'music', 'late',
   '{"schema_version":1,"summary":"Familiar tunes played softly and hummed along to, in a small circle.","minutes":15,"group_friendly":true,"sensory":true,"formats":["active","sensory"],"themes":["music"]}'),
  ('5eed0000-0000-4000-8000-000000000022', 'Easy crossword', 'word', 'early',
   '{"schema_version":1,"summary":"A 9 by 9 crossword in large print, with a picture clue beside each word.","minutes":25,"group_friendly":false,"sensory":false,"formats":["games","printable"]}'),
  ('5eed0000-0000-4000-8000-000000000023', 'Word scramble: spring', 'word', 'early',
   '{"schema_version":1,"summary":"Spring words with the letters mixed up and a picture clue for each.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"],"themes":["spring","garden"],"template":{"generator":"scramble","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000024', 'Word scramble: the sky', 'word', 'early',
   '{"schema_version":1,"summary":"Flight words (wing, pilot, runway) with the letters mixed up.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"],"themes":["aviation"],"template":{"generator":"scramble","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000025', 'Large-print sudoku', 'numbers', 'early',
   '{"schema_version":1,"summary":"4 by 4 and 6 by 6 puzzles with one solution each.","minutes":20,"group_friendly":false,"sensory":false,"formats":["games","printable"],"template":{"generator":"mini-sudoku","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000026', 'Money counting', 'numbers', 'early',
   '{"schema_version":1,"summary":"Coins at true size with old-time prices: a ready group conversation.","minutes":20,"group_friendly":true,"sensory":false,"formats":["games","printable"],"themes":["nostalgia-1950s"],"template":{"generator":"money-count","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000027', 'Singer and song match', 'music', 'early',
   '{"schema_version":1,"summary":"Match singers to their songs, or songs to their years.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"],"themes":["music","nostalgia-1960s"],"template":{"generator":"singer-match","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000028', 'Alphabet sweep: the garden', 'letters', 'early',
   '{"schema_version":1,"summary":"One theme, A to Z: a natural group brainstorm.","minutes":20,"group_friendly":true,"sensory":false,"formats":["games"],"themes":["garden","spring"],"template":{"generator":"alphabet-sweep","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000029', 'Name three', 'word', 'universal',
   '{"schema_version":1,"summary":"Naming prompts; one answer is plenty at the advanced stage.","minutes":15,"group_friendly":true,"sensory":false,"formats":["games"],"template":{"generator":"name-three","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000030', 'Goes together', 'word', 'middle',
   '{"schema_version":1,"summary":"Everyday pairs such as salt and pepper, in fewer and larger pieces.","minutes":15,"group_friendly":true,"sensory":false,"formats":["games"],"themes":["home-kitchen"],"template":{"generator":"goes-together","params":{}}}'),
  ('5eed0000-0000-4000-8000-000000000031', 'Matching pairs: everyday objects', 'word', 'middle',
   '{"schema_version":1,"summary":"Six large picture cards to match, such as a cup and its saucer.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"],"themes":["home-kitchen"]}'),
  ('5eed0000-0000-4000-8000-000000000032', 'Large dot-to-dot', 'numbers', 'middle',
   '{"schema_version":1,"summary":"A simple picture that appears as the dots are joined in order.","minutes":15,"group_friendly":false,"sensory":false,"formats":["games","printable"]}'),
  ('5eed0000-0000-4000-8000-000000000033', 'Recipe cards to read aloud', 'word', 'middle',
   '{"schema_version":1,"summary":"Large-print family-style recipes to read aloud and talk about.","minutes":20,"group_friendly":true,"sensory":false,"formats":["printable","reminiscence"],"themes":["home-kitchen","nostalgia-1950s"]}'),
  ('5eed0000-0000-4000-8000-000000000034', 'Large-piece puzzle', 'word', 'late',
   '{"schema_version":1,"summary":"A six to twelve piece puzzle with big, thick pieces and a clear picture.","minutes":20,"group_friendly":false,"sensory":true,"formats":["games"]}'),
  ('5eed0000-0000-4000-8000-000000000035', 'Sorting buttons', 'word', 'late',
   '{"schema_version":1,"summary":"Sort large buttons by color into bowls: familiar, tactile and calming.","minutes":15,"group_friendly":false,"sensory":true,"formats":["games","sensory"],"themes":["home-kitchen"],"materials":["Large buttons (too big to swallow)","Shallow bowls"]}'),
  ('5eed0000-0000-4000-8000-000000000036', 'Coloring: spring flowers', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold line art of spring flowers.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"themes":["spring","garden"]}'),
  ('5eed0000-0000-4000-8000-000000000037', 'Coloring: airplanes', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold line art of classic airplanes.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"themes":["aviation"]}'),
  ('5eed0000-0000-4000-8000-000000000038', 'Coloring: classic cars', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold line art of 1950s cars.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"themes":["road-trips","nostalgia-1950s"]}'),
  ('5eed0000-0000-4000-8000-000000000039', 'Coloring: autumn leaves', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold line art of autumn leaves.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"themes":["autumn"]}'),
  ('5eed0000-0000-4000-8000-000000000040', 'Coloring: winter cottage', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold line art of a snowy cottage.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"themes":["winter"]}'),
  ('5eed0000-0000-4000-8000-000000000041', 'Coloring: summer picnic', 'cognicopia-coloring', 'universal',
   '{"schema_version":1,"summary":"Bold line art of a picnic by the lake.","minutes":30,"group_friendly":true,"sensory":true,"formats":["printable"],"themes":["summer"]}'),
  ('5eed0000-0000-4000-8000-000000000042', 'Seasons photo sheet', 'multisensory', 'universal',
   '{"schema_version":1,"summary":"Large seasonal photographs with one word each, to look at and talk about.","minutes":15,"group_friendly":true,"sensory":true,"formats":["printable","sensory"],"themes":["spring","summer","autumn","winter"]}'),
  ('5eed0000-0000-4000-8000-000000000043', 'Hand massage', 'multisensory', 'late',
   '{"schema_version":1,"summary":"A gentle hand massage with a lotion the person''s skin is known to tolerate.","minutes":15,"group_friendly":false,"sensory":true,"formats":["sensory"],"steps":["Ask first, and stop if the person pulls away.","Check care plans and skin for allergies or sensitivity."]}'),
  ('5eed0000-0000-4000-8000-000000000044', 'Texture box', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Soft, smooth and rough fabrics to hold and sort by feel.","minutes":15,"group_friendly":false,"sensory":true,"formats":["sensory"],"materials":["Velvet, flannel, silk, wool swatches"]}'),
  ('5eed0000-0000-4000-8000-000000000045', 'Aroma moments', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Fresh herbs and lavender sachets to smell, one at a time.","minutes":15,"group_friendly":false,"sensory":true,"formats":["sensory"],"themes":["spring","garden"],"steps":["Check for allergies and sensitivities first.","Offer one scent at a time, with a pause between."]}'),
  ('5eed0000-0000-4000-8000-000000000046', 'Window bird watching', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Sit by a window with a bird feeder and share short comments on what comes.","minutes":20,"group_friendly":true,"sensory":true,"formats":["sensory"],"themes":["garden","spring","winter"]}'),
  ('5eed0000-0000-4000-8000-000000000047', 'Watching the sky', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Watch the clouds and any airplanes pass from a window or the patio.","minutes":20,"group_friendly":true,"sensory":true,"formats":["sensory"],"themes":["aviation","summer"]}'),
  ('5eed0000-0000-4000-8000-000000000048', 'Airport sounds', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Recordings of propeller engines and jets, played quietly one at a time, with a model plane to hold.","minutes":15,"group_friendly":true,"sensory":true,"formats":["sensory"],"themes":["aviation"],"materials":["Quiet recordings of airplane engines","A light model airplane"],"steps":["Play one sound at a time and pause between them.","Offer the model to hold, and watch for comfort."]}'),
  ('5eed0000-0000-4000-8000-000000000049', 'Cloud shapes', 'multisensory', 'middle',
   '{"schema_version":1,"summary":"Look at large photographs of clouds and sky, and name the shapes together.","minutes":20,"group_friendly":true,"sensory":true,"formats":["sensory","games"],"themes":["aviation","summer"],"materials":["Large photographs of clouds and sky"]}'),
  ('5eed0000-0000-4000-8000-000000000050', 'Fly a kite', 'movement', 'middle',
   '{"schema_version":1,"summary":"A light kite flown on the patio on a calm day, with a helper to hold the line.","minutes":25,"group_friendly":true,"sensory":true,"formats":["active"],"themes":["aviation","spring"],"materials":["A light kite with a long line"]}'),
  ('5eed0000-0000-4000-8000-000000000051', 'Flight crossword', 'word', 'early',
   '{"schema_version":1,"summary":"A large-print crossword of flight words with a word bank.","minutes":20,"group_friendly":false,"sensory":false,"formats":["games","printable"],"themes":["aviation"]}'),
  ('5eed0000-0000-4000-8000-000000000052', 'Airplane memory cards', 'word', 'middle',
   '{"schema_version":1,"summary":"Large photographs of airplanes from propellers to jets to turn over and match.","minutes":20,"group_friendly":true,"sensory":false,"formats":["games","reminiscence"],"themes":["aviation","nostalgia-1950s"],"materials":["Large photographs of airplanes, printed in pairs"]}'),
  ('5eed0000-0000-4000-8000-000000000053', 'Warm towel folding', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Fold warm, freshly dried towels: a familiar task with a comforting feel.","minutes":15,"group_friendly":true,"sensory":true,"formats":["sensory"],"themes":["home-kitchen"]}'),
  ('5eed0000-0000-4000-8000-000000000054', 'Photo album browse', 'multisensory', 'late',
   '{"schema_version":1,"summary":"Large-print books of vintage photographs to turn through together.","minutes":20,"group_friendly":true,"sensory":true,"formats":["sensory","reminiscence"],"themes":["nostalgia-1950s","nostalgia-1960s"]}'),
  ('5eed0000-0000-4000-8000-000000000055', 'Baking day aromas', 'multisensory', 'middle',
   '{"schema_version":1,"summary":"Bake something simple so the unit fills with a familiar smell.","minutes":30,"group_friendly":true,"sensory":true,"formats":["sensory","reminiscence"],"themes":["home-kitchen","autumn","winter"],"steps":["Check each person''s diet and swallowing guidance before offering a taste.","Let people measure, pour or stir."]}'),
  ('5eed0000-0000-4000-8000-000000000056', 'Autumn leaf sort', 'multisensory', 'middle',
   '{"schema_version":1,"summary":"Sort real leaves by color and shape and feel their edges.","minutes":20,"group_friendly":true,"sensory":true,"formats":["sensory","games"],"themes":["autumn","garden"]}'),
  ('5eed0000-0000-4000-8000-000000000057', 'Finish the saying', 'trivia', 'universal',
   '{"schema_version":1,"summary":"Familiar sayings to finish aloud, together.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"questions":[{"q":"A penny saved is a penny ...","a":"earned"},{"q":"Better late than ...","a":"never"},{"q":"Many hands make ...","a":"light work"},{"q":"An apple a day keeps the ... away","a":"doctor"},{"q":"A stitch in time saves ...","a":"nine"}]}'),
  ('5eed0000-0000-4000-8000-000000000058', 'Familiar songs: finish the line', 'trivia', 'middle',
   '{"schema_version":1,"summary":"Song titles to finish together, with the tune hummed to help.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"themes":["music","nostalgia-1950s"],"questions":[{"q":"You Are My ...","a":"Sunshine"},{"q":"Take Me Out to the ...","a":"Ball Game"},{"q":"Row, row, row your ...","a":"boat"},{"q":"Home, home on the ...","a":"range"}]}'),
  ('5eed0000-0000-4000-8000-000000000059', 'Spring in the garden', 'trivia', 'early',
   '{"schema_version":1,"summary":"Easy questions about spring, flowers and weather.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"themes":["spring","garden"],"questions":[{"q":"Which bird is a famous sign of spring: a robin or a penguin?","a":"A robin"},{"q":"What do bees collect from flowers?","a":"Nectar"},{"q":"Which is planted in autumn to bloom in spring: tulip bulbs or tomato seeds?","a":"Tulip bulbs"},{"q":"April showers bring what?","a":"May flowers"}]}'),
  ('5eed0000-0000-4000-8000-000000000060', 'Up in the air', 'trivia', 'early',
   '{"schema_version":1,"summary":"Questions about flying, from the first airplane onward.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"themes":["aviation"],"questions":[{"q":"Which brothers made the first powered airplane flight, in 1903?","a":"The Wright brothers"},{"q":"In which state, at Kitty Hawk, did they fly?","a":"North Carolina"},{"q":"What is the long strip where airplanes take off called?","a":"A runway"},{"q":"Which pilot flew alone and nonstop across the Atlantic in 1927?","a":"Charles Lindbergh"}]}'),
  ('5eed0000-0000-4000-8000-000000000061', 'Classic television', 'trivia', 'middle',
   '{"schema_version":1,"summary":"Gentle questions about favorite shows of the 1950s and 1960s.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"themes":["nostalgia-1950s","nostalgia-1960s"],"questions":[{"q":"In I Love Lucy, what was Lucy''s husband called: Ricky or Fred?","a":"Ricky"},{"q":"On which night was The Ed Sullivan Show famously on: Sunday or Wednesday?","a":"Sunday"},{"q":"In The Andy Griffith Show, was Andy the sheriff or the barber?","a":"The sheriff"}]}'),
  ('5eed0000-0000-4000-8000-000000000062', 'Kitchen and home', 'trivia', 'universal',
   '{"schema_version":1,"summary":"Everyday questions about cooking and the home.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"themes":["home-kitchen"],"questions":[{"q":"What makes bread rise: yeast or salt?","a":"Yeast"},{"q":"Before refrigerators, what kept food cold: an ice box or a toaster?","a":"An ice box"},{"q":"Which belongs on the stove: a skillet or a rake?","a":"A skillet"}]}'),
  ('5eed0000-0000-4000-8000-000000000063', 'Sing and say together', 'trivia', 'late',
   '{"schema_version":1,"summary":"Two or three very familiar lines, started for the person to finish.","minutes":10,"group_friendly":true,"sensory":true,"formats":["trivia","active"],"themes":["music"],"questions":[{"q":"Twinkle, twinkle, little ...","a":"star"},{"q":"Amazing grace, how sweet the ...","a":"sound"},{"q":"Jingle bells, jingle bells, jingle all the ...","a":"way"}]}'),
  ('5eed0000-0000-4000-8000-000000000064', 'Finish the song', 'trivia', 'universal',
   '{"schema_version":1,"summary":"Famous song titles to finish, called out as a group.","minutes":15,"group_friendly":true,"sensory":false,"formats":["trivia"],"themes":["music"],"template":{"generator":"finish-song","params":{}},"questions":[{"q":"Good night, ...","a":"Irene"},{"q":"I''ve Been Working on the ...","a":"Railroad"},{"q":"Let Me Call You ...","a":"Sweetheart"}]}'),
  ('5eed0000-0000-4000-8000-000000000065', 'The radio after supper', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"Families gathered around the radio in the evening. What did your household listen to?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","music"],"decade":1940,"senses":["sound"],"follow_ups":["Was there a favorite program, or a favorite voice?","Where did the radio sit in the room?","Who got the best seat?"]}'),
  ('5eed0000-0000-4000-8000-000000000066', 'Saturday night at the dance hall', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Big bands filled dance halls on a Saturday night. Tell me about a night out dancing.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","music"],"decade":1940,"senses":["sound"],"follow_ups":["Dancing, or watching the dancers?","A slow song or a fast one?"]}'),
  ('5eed0000-0000-4000-8000-000000000067', 'Sunday dinner in the oven', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"A Sunday roast filled many homes with its smell by noon. Tell me what Sunday dinner smelled like at your house.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","home-kitchen"],"decade":1940,"senses":["smell","taste"],"follow_ups":["Roast chicken or roast beef?","A big table or a small one?"],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}'),
  ('5eed0000-0000-4000-8000-000000000068', 'Ice cream on a hot day', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"Ice cream was a real treat on a hot day. Vanilla or chocolate?","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","summer"],"decade":1940,"senses":["taste"],"follow_ups":["Vanilla, with a cherry on top.","A cool, sweet taste on a warm day."],"steps":["Check each person''s diet and swallowing guidance before offering any taste."],"materials":["Ice cream, only if the diet allows"]}'),
  ('5eed0000-0000-4000-8000-000000000069', 'A wool coat', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"Wool coats kept everyone warm through the winter. Feel this wool: how does it compare to what you wore?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s"],"decade":1940,"senses":["touch"],"follow_ups":["Was your coat heavy, or light?","Who did the mending?"],"materials":["A wool swatch"]}'),
  ('5eed0000-0000-4000-8000-000000000070', 'The streetcar on the corner', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Streetcars ran through many towns. Tell me where the streetcar took you.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","road-trips"],"decade":1940,"senses":["sight"],"follow_ups":["A ride with family or with friends?","Standing, or finding a seat?"]}'),
  ('5eed0000-0000-4000-8000-000000000071', 'The party-line telephone', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"Many homes shared a telephone line with the neighbors. Tell me about the telephone at your house.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s"],"decade":1940,"senses":["sound"],"follow_ups":["Was it on the wall or on a table?","Who called most often?"]}'),
  ('5eed0000-0000-4000-8000-000000000072', 'Wash day and the clothesline', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Clothes dried in the sun on a line, and the sheets smelled wonderful. Tell me about wash day.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","home-kitchen"],"decade":1940,"senses":["sight","smell"],"follow_ups":["Hanging sheets, or folding them?","Sunny days, or windy ones?"]}'),
  ('5eed0000-0000-4000-8000-000000000073', 'Fresh-cut grass', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"The smell of a freshly mown lawn means summer is here. Warm sun, and fresh grass.","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s","summer","garden"],"decade":1940,"senses":["smell"],"follow_ups":["Soft, green grass.","A shady spot on the porch."],"materials":["A handful of fresh-cut grass, if available"]}'),
  ('5eed0000-0000-4000-8000-000000000074', 'Cards at the kitchen table', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"Cards on the kitchen table after supper were a favorite pastime. What games did your family play?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1940s"],"decade":1940,"senses":["touch","sight"],"follow_ups":["Who played to win?","Who dealt?"],"materials":["A deck of playing cards"]}'),
  ('5eed0000-0000-4000-8000-000000000075', 'The first television', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"Many families got their first television in the 1950s. Tell me about the first one you watched.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s"],"decade":1950,"senses":["sight"],"follow_ups":["What did the family watch together?","Who sat closest to the screen?"]}'),
  ('5eed0000-0000-4000-8000-000000000076', 'Rock and roll on the radio', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"A new kind of music took over the radio in the 1950s. Tell me about the music you liked to listen to.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s","music"],"decade":1950,"senses":["sound"],"follow_ups":["Dancing to it, or just listening?","Did the family like it, or not so much?"]}'),
  ('5eed0000-0000-4000-8000-000000000077', 'The soda fountain', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"A root beer float at the soda fountain was a favorite treat. What was your order?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s"],"decade":1950,"senses":["taste"],"follow_ups":["A float, or a milkshake?","Who did you go with?"],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}'),
  ('5eed0000-0000-4000-8000-000000000078', 'Saturday at the movies', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"A Saturday matinee was an outing for many families. Tell me about a favorite trip to the movies.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s"],"decade":1950,"senses":["sight"],"follow_ups":["What did you see?","What did you buy at the counter?"]}'),
  ('5eed0000-0000-4000-8000-000000000079', 'Dressed up for Sunday', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"Starched collars and pressed dresses were the Sunday way. Feel this cotton: what was Sunday dress like?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s"],"decade":1950,"senses":["touch"],"follow_ups":["Crisp, or soft?","Who ironed the shirts?"],"materials":["A starched cotton swatch"]}'),
  ('5eed0000-0000-4000-8000-000000000080', 'The jukebox', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"A nickel bought a song at the diner. Tell me about a song you might have played.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s","music"],"decade":1950,"senses":["sound"],"follow_ups":["Dancing along, or tapping a foot?","Picking the song, or letting a friend pick?"]}'),
  ('5eed0000-0000-4000-8000-000000000081', 'The new car', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"A new car''s smell, with its fresh seats, was a big event. Tell me about your family''s car.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s","road-trips"],"decade":1950,"senses":["smell","sight"],"follow_ups":["What color was it?","Where did you drive first?"]}'),
  ('5eed0000-0000-4000-8000-000000000082', 'The Hula-Hoop craze', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"In 1958 the Hula-Hoop swept the country. Tell me about trying one.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s","summer"],"decade":1950,"senses":["sight","touch"],"follow_ups":["Around the waist, or around an arm?","In the yard, or in the street?"],"materials":["A hoop, if the group would like to try"]}'),
  ('5eed0000-0000-4000-8000-000000000083', 'The backyard barbecue', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Charcoal smoke meant a summer cookout. Tell me what was on the grill at your house.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s","summer"],"decade":1950,"senses":["smell","taste"],"follow_ups":["Burgers or hot dogs?","Corn on the cob, or potato salad?"],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}'),
  ('5eed0000-0000-4000-8000-000000000084', 'A soft bedspread', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"Soft chenille bedspreads were in many bedrooms. Feel this soft fabric: cozy.","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1950s","home-kitchen"],"decade":1950,"senses":["touch"],"follow_ups":["Soft and warm.","A quilt on the bed."],"materials":["A chenille or soft cotton blanket"]}'),
  ('5eed0000-0000-4000-8000-000000000085', 'The Beatles on television', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"In February 1964 the Beatles appeared on The Ed Sullivan Show. Tell me about the music of those years.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","music"],"decade":1960,"senses":["sound"],"follow_ups":["Who in the family liked it?","Did you have a favorite song?"]}'),
  ('5eed0000-0000-4000-8000-000000000086', 'Motown', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Motown songs got everyone dancing. Tell me a song that makes you tap your foot.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","music"],"decade":1960,"senses":["sound"],"follow_ups":["Dancing with a partner, or on your own?","On the radio, or at a party?"]}'),
  ('5eed0000-0000-4000-8000-000000000087', 'Watching the moon landing', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"In July 1969 people all over the world watched the moon landing on television. Tell me about that evening.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","aviation"],"decade":1960,"senses":["sight"],"follow_ups":["Who watched with you?","What was the room like?"]}'),
  ('5eed0000-0000-4000-8000-000000000088', 'A Polaroid photograph', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"Polaroid cameras gave you the picture in minutes. Hold this photograph: tell me about a favorite snapshot.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s"],"decade":1960,"senses":["touch","sight"],"follow_ups":["Who is in it?","Where was it taken?"],"materials":["An old photograph or a photo print"]}'),
  ('5eed0000-0000-4000-8000-000000000089', 'Coffee on the stove', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"A percolator bubbling on the stove meant morning had begun. Tell me about your mornings.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","home-kitchen"],"decade":1960,"senses":["smell"],"follow_ups":["Up early, or sleeping in?","Toast, or a sweet roll?"],"materials":["Freshly brewed coffee, if the diet allows the smell and a sip"]}'),
  ('5eed0000-0000-4000-8000-000000000090', 'Lemonade at the picnic', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"Lemonade at a picnic on a warm day: cool and sweet.","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","summer"],"decade":1960,"senses":["taste"],"follow_ups":["Sweet or tart?","Cold in the cup."],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}'),
  ('5eed0000-0000-4000-8000-000000000091', 'Folk songs and guitars', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"Guitars and folk songs were everywhere in the early 1960s. Tell me about singing or playing in those days.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","music"],"decade":1960,"senses":["sound"],"follow_ups":["Who played?","Which song did everyone know?"]}'),
  ('5eed0000-0000-4000-8000-000000000092', 'The family station wagon', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"The station wagon carried the whole family on vacation. Tell me about a family vacation.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","road-trips"],"decade":1960,"senses":["sight"],"follow_ups":["Window seat, or the middle?","A picnic, or a stop at a diner?"]}'),
  ('5eed0000-0000-4000-8000-000000000093', 'A crocheted blanket', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"Handmade crocheted blankets were found in many living rooms. Feel the soft yarn: warm and cozy.","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","home-kitchen"],"decade":1960,"senses":["touch"],"follow_ups":["Soft yarn.","Cozy in the chair."],"materials":["A crocheted afghan or soft yarn"]}'),
  ('5eed0000-0000-4000-8000-000000000094', 'Learning the Twist', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"The Twist dance craze began in 1960. Tell me about dancing in those days.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1960s","music"],"decade":1960,"senses":["sound"],"follow_ups":["Where did you dance?","Who was the best dancer?"]}'),
  ('5eed0000-0000-4000-8000-000000000095', 'Disco nights', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"Disco filled dance floors in the late 1970s. Tell me about a night of dancing.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","music"],"decade":1970,"senses":["sound"],"follow_ups":["What did you wear?","Who did you go with?"]}'),
  ('5eed0000-0000-4000-8000-000000000096', 'Harvest gold and avocado green', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Kitchens in the 1970s were often harvest gold or avocado green. Tell me about the color of your kitchen.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","home-kitchen"],"decade":1970,"senses":["sight"],"follow_ups":["The stove, or the refrigerator?","Cooking on your own, or with company?"]}'),
  ('5eed0000-0000-4000-8000-000000000097', 'The CB radio', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Truckers and families used CB radios in the 1970s. Tell me about road trips in those days.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","road-trips"],"decade":1970,"senses":["sound"],"follow_ups":["A CB handle, or just a radio?","A short trip, or a long one?"]}'),
  ('5eed0000-0000-4000-8000-000000000098', 'Shag carpet', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"Shag carpet was soft underfoot. Feel this shaggy fabric: what was the carpet like at home?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","home-kitchen"],"decade":1970,"senses":["touch"],"follow_ups":["What color was it?","Who vacuumed it?"],"materials":["A shaggy fabric or fleece swatch"]}'),
  ('5eed0000-0000-4000-8000-000000000099', 'Fondue and Jell-O', 'reminiscence', 'universal',
   '{"schema_version":1,"summary":"Fondue pots and Jell-O molds were dinner party favorites. Tell me about a dinner you hosted or enjoyed.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","home-kitchen"],"decade":1970,"senses":["taste"],"follow_ups":["A small party, or a big one?","Fondue, or Jell-O?"],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}'),
  ('5eed0000-0000-4000-8000-000000000100', 'Bread in the oven', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"Homemade bread in the oven smells like home. Warm and sweet.","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","home-kitchen"],"decade":1970,"senses":["smell"],"follow_ups":["Warm, fresh bread.","The kitchen on a cold day."],"materials":["A loaf of fresh bread, if the diet allows"],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}'),
  ('5eed0000-0000-4000-8000-000000000101', 'Saturday morning cartoons', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"Saturday morning cartoons, with a bowl of cereal, were a ritual for many children. What was Saturday morning like at your house?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s"],"decade":1970,"senses":["sight"],"follow_ups":["Who woke up first?","What was the favorite show?"]}'),
  ('5eed0000-0000-4000-8000-000000000102', 'The Mary Tyler Moore Show', 'reminiscence', 'early',
   '{"schema_version":1,"summary":"The Mary Tyler Moore Show ran from 1970 to 1977. Tell me about a favorite show of that decade.","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s"],"decade":1970,"senses":["sound","sight"],"follow_ups":["Who watched with you?","Which theme song could you hum?"]}'),
  ('5eed0000-0000-4000-8000-000000000103', 'Macramé and plant hangers', 'reminiscence', 'middle',
   '{"schema_version":1,"summary":"Macramé plant hangers hung in many windows. Feel this knotted cord: did anyone you know make them?","minutes":20,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","garden"],"decade":1970,"senses":["touch"],"follow_ups":["What plant hung in yours?","Who taught you to knot?"],"materials":["A length of knotted cord"]}'),
  ('5eed0000-0000-4000-8000-000000000104', 'Iced tea on the porch', 'reminiscence', 'late',
   '{"schema_version":1,"summary":"A cold glass of iced tea on the porch: cool and refreshing.","minutes":10,"group_friendly":true,"sensory":true,"formats":["reminiscence"],"themes":["nostalgia-1970s","summer"],"decade":1970,"senses":["taste","smell"],"follow_ups":["Lemon, or plain?","Cool in the glass."],"steps":["Check each person''s diet and swallowing guidance before offering any taste."]}')
on conflict (id) do nothing;
